services:
  actual:
    image: docker.io/actualbudget/actual-server:latest
    container_name: ${APP}
    labels:
      tsdproxy.enable: true
      tsdproxy.name: ${APP}
    ports:
      - '5006:5006'
    volumes:
      - ${DOCKER_APPS}/${APP}:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always